- include: check-deploy-needed.yml

- include: deploy.yml
  when: tomcat_app_needs_deploy

- include: configure.yml

- name: Make sure tomcat is started
  meta: flush_handlers

- include: tests.yml

- include: enable-in-haproxy.yml
