# install.yml
---
- hosts: all
  gather_facts: true
  become: true
  roles:
  - role: common
    tags: common

- hosts: load-balancers
  gather_facts: false
  become: true
  roles:
  - role: haproxy
    tags: haproxy

- hosts: app-servers
  become: true
  gather_facts: false
  roles:
  - role: tomcat
    tags: tomcat
